[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "light"
primaryColor = "#1db954"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"
